version: '3'

services:
   nginx:
      build:
         context: ./
         dockerfile: Dockerfile.nginx
      environment:
         - NGINX_HOST=botanist-webapp
         - NGINX_PORT=9090
      ports:
         - 80:80
      command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

   botanist-webapp:
      build:
         context: ./
         dockerfile: Dockerfile
      ports:
         - 9090
      env_file:
         - ./env
      volumes:
         - $HOME/botanist/repos:/botanist/repos
