FROM nginx:1.13.5

# from https://raw.githubusercontent.com/nginx/nginx/master/conf/uwsgi_params
ADD uwsgi_params /etc/nginx/uwsgi_params
ADD ./etc/nginx/nginx.conf.template /etc/nginx/nginx.conf.template

ADD ./webapp/botanist-static /data/static
